name: Deploy

on:
  push:
    branches:
      - temp

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # This version will work fine with Node.js 20

      - name: Setup Node
        uses: actions/setup-node@v4  # Use v4 to avoid deprecation with Node.js 20
        with:
          node-version: 18

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4  # Updated to v4 for Node.js 20 support
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2  # This version is still fine

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # This version is still fine
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
